version: '3.3'

services:
  php:
    build: 
      context: .
      dockerfile: .docker/php/Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/var/www
      - ./.docker/php/getlaminas.ini:/usr/local/etc/php/conf.d/999-getlaminas.ini
      - ./.docker/php/php-entrypoint:/usr/local/bin/php-entrypoint
  
  nginx:
    build: .docker/nginx/
    depends_on:
      - php
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - .:/var/www
